### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by alexjj** [pierrechevalier83/ferris#22]
The link on https://www.cuddlykeyboards.com/ has expired.

**Comment by keyboard-magpie** [comment]
We had a raft of bots raiding the server, had to reset them all. Here is a new permalink: https://discord.gg/69UM9sQF8q

**Comment by pierrechevalier83** [comment]
Thanks @alexjj for the report and @keyboard-magpie for the new link. I've updated the website.
