### ISSUE TITLE
Is fuse programming required?

### ISSUE THREAD

**Issue by yejianfengblue** [pierrechevalier83/ferris#26]
[This website](https://www.partsnotincluded.com/sparkfun-pro-micro-with-usb-a/) says building a pro micro board needs to programming the fuse bits. Is fuse programming required for ferris v0.1 (atmega32u4 mcu with fuse) and ferris 0.2 (stm32 mcu with fuse)?

**Comment by keyboard-magpie** [comment]
v0.1- atmega32u4- not usually unless you buy an RC part number- most come with DFU on from the factory
v0.2- stm32- no- not at all

**Comment by yejianfengblue** [comment]
Many thanks for your quick reply.
