### ISSUE TITLE
Does I2C over TRRS suffers from reliability issues?

### ISSUE THREAD

**Issue by hochshi** [pierrechevalier83/ferris#27]
Hi,
I thought this would be the right place to ask this.
I'm modifying a crkdb and would like to replace one MCU with a MCP23017/8 GPIO expander.
I'm currently using the two halves of the keyboard really far apart, around one meter. Resources online suggest running I2C over one meter would cause interference between SDA and SCL and so using a TRRS is unadvisable.
For more info see: https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/How-to-make-a-reliable-I2C-bus

Have you noticed any issues with that?
Do you suggest using a specific type of TRRS cable?
Have you taken these into account when choosing the pullup resistors?

Thanks

**Comment by pierrechevalier83** [comment]
I'm using a pretty short cable myself, but I've used 1m long cables without any issues.
The pullup resistors are 4.7kOhm on SDA and SCL and the chips on the 0.2 versions operate at 3.3V, so the current is under 1mA (~0.7mA), which should be well within margin according to the link you shared. They say you might encounter problems above 3mA.

**Comment by hochshi** [comment]
Thank you.
