### ISSUE TITLE
[bling 0.2] Is RGB underglow visible throught the keycaps

### ISSUE THREAD

**Issue by robinmoussu** [pierrechevalier83/ferris#28]
With a group of friend we are planning to build ferris bling 0.2. We are looking at [those white keycaps](https://splitkb.com/collections/switches-and-keycaps/products/moergo-mcc-profile-1u-keycap?variant=42898211635459). They are translucent which let the light goes through, but is it visible on the ferris since the leds seems to be only under the pcb?

**Comment by pierrechevalier83** [comment]
No, the RGBs are under the PCB and there aren't any cutouts, so translucent keycaps won't look particularly nice on the Bling.

**Comment by robinmoussu** [comment]
I forgot to say thank you!
