### ISSUE TITLE
Why the choice on TRRS cable ?

### ISSUE THREAD

**Issue by Velasko** [pierrechevalier83/ferris#30]
Checking at the schematics, seems like 2 pins are used for vcc and one for gnd.
Changing it to ( vcc | gnd | data | data ) would make it compatible with both trs and trrs cables and sockets.

**Comment by quarthex** [comment]
I just checked the schematics.

Jack0: i2c_scl, i2c_sda, +3V3, GND
Jack1: i2c_scl_right, i2c_sda_right, VDD, GND

It looks good to me.

**Comment by Velasko** [comment]
Hello !

It's not that it doesn't work as is, it really does.
However, the suggestion is to support TRS cable while keeping the TRRS option.

From what I remember (it's been a while), the redundant ring was at the base of the jack. So, on TRS cables, VCC and ground would short-circuit. However, if the doubled channel (data) was at the tip, it wouldn't be a problem.

At least, I remember not having a differential data transfer, like usb does. So only 3 'wires' were needed.

**Comment by keyboard-magpie** [comment]
You can't talk to an i2c port expander over 3 terminals. You need 4.

To drop to 3 terminals you would have to rework the secondary half to have an MCU speaking USART, which somewhat goes against the original design intent.

**Comment by Velasko** [comment]
Oh, I see now.

I was actually looking into a fork of the project, which has a microcontroller on both ends, which allows that.
I suppose they kept that in order to change the original board as little as possible.

When I noticed that, I thought on creating the issue there, but noticed this also happened here. Thought it would be better to ask things here.

Thanks for the explanation and sorry for the inattentiveness.

Will close the issue as it has been clearly answered now.
