### ISSUE TITLE
Where to buy a kit?

### ISSUE THREAD

**Issue by rmwphd** [pierrechevalier83/ferris#4]
Are kit purchases still available for this keyboard (esp. Compact, Bling, or Mini revs)? 

I couldn't find a website link in the Readme.md.

**Comment by MangoIV** [comment]
The newer revs are still in the prototype my stage. I guess you gotta be patient :)

**Comment by mreed20** [comment]
@rmwphd A kit would definitely be more convenient, but I found that it was actually pretty easy to order the parts from https://lcsc.com (using their "BOM Tool" to upload the bill of materials, `bom.csv`) and  PCB from https://jlcpcb.com (I uploaded the PCB schematic to the website and everything else was automatic).

**Comment by rmwphd** [comment]
Hmm! Thanks for the tip, Michael! 

Nice last name btw ;-)

**Comment by mreed20** [comment]
Many thanks, Reed :)

**Comment by pierrechevalier83** [comment]
I still haven't got working firmware for my a prototypes, so I would advise for waiting it out or going with the previous arm revisions if you really want a kit now 🙂

**Comment by rmwphd** [comment]
~We will watch your career with great interest.~ 

I'll wait patiently and maybe try kitting out an older rev for myself.

**Comment by pierrechevalier83** [comment]
Hi Reed,

I know it's been a long while, but if you're still interested, I just
started a group buy for the latest version of the Ferris keyboard.

Here is a form that you can fill out if you would like to get one. I plan
to ship orders in a month or so.

https://docs.google.com/forms/d/1T0Kk4zi-_mEqnTM6SoopiEEtbMQLUm-RHTR6Tu1Jl-o

All the best,
Pierre

**Comment by rmwphd** [comment]
Thanks for the note, Pierre! I'll be sure to sign up :-)

**Comment by MoSchaub** [comment]
I signed up in the form and I was wondering if there was any confirmation email because I didn't receive anything

**Comment by pierrechevalier83** [comment]
Hi Moritz,

Thanks for registering your interest.

Sorry, there isn't a confirmation email. I'll be giving updates on slack
and by email as things progress.

All the best,
Pierre
